package it.polimi.ingsw.pc34.Controller;

/**
 * Created by Povaz on 20/06/2017.
 */
public enum PlayerState {
    PLAY_TURN, ACTION, ACTION_INPUT, ACTION_TYPE, ACTION_SPOT, FAMILY_MEMBER,
    SERVANTS, EXCHANGE_COUNCIL_PRIVILEGE, CHOOSE_TRADE, ASK_WHICH_DISCOUNT,
    PLACE_LEADER_CARD, ASK_WHICH_CARD_COPY, ACTIVATE_LEADER_CARD,
    FAMILY_MEMBER_NOT_NEUTRAL, EXCHANGE_LEADER_CARD, WAITING,
    SUPPORT_VATICAN, CHAT, STAMPINFO
}
